apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zipkin
  namespace: argocd
spec:
  destination:
    namespace: asset
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: bootstrap/zipkin
    repoURL: 'https://github.com/finndev2024/asset-apps-argocd.git'
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
