apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
  namespace: asset
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server

  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          #          image: finndev2024/eureka-server:latest
          image: finndev2024/eureka-server:6.7
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: azure
          resources:
            requests:
              memory: 576Mi
      # nodeSelector:
      #   app: api-apps
