apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: asset
  labels:
    app: eureka-server
spec:
  type: ClusterIP
  selector:
    app: eureka-server
  ports:
    - port: 8761
      targetPort: 8761
