apiVersion: v1
kind: Service
metadata:
  name: api-posts
  namespace: asset
  labels:
    app: api-posts
spec:
  type: NodePort
  selector:
    app: api-posts
  ports:
    - port: 80
      targetPort: 8089