apiVersion: v1
kind: Service
metadata:
  name: api-customers
  namespace: asset
  labels:
    app: api-customers
spec:
  selector:
    app: api-customers
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort