apiVersion: v1
kind: Service
metadata:
  name: api-users
  namespace: asset
  labels:
    app: api-users
spec:
  type: NodePort
  selector:
    app: api-users
  ports:
    - port: 80
      targetPort: 9090